# Generated by Django 4.2.1 on 2023-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'News'},
        ),
    ]
